### ISSUE TITLE
Streetview coma coordinates

### ISSUE THREAD

**Issue by notebooker** [roemhildtg/arcgis-pro-addins#1]
Hi, thanks for the add-in!!!
I tested the Streetview add-in and I think it will be working (it opens web browser on google maps) but in my case, the coordinates given to browser has coma decimals separator. I think its because my Czech (Europe) Windows, am I right? And is it possible to handle it in your add-in?
Thank you very much, Petr B.

**Comment by green3g** [comment]
Hmm, thats interesting. Can you post the url that it generates?

**Comment by notebooker** [comment]
First it generates this URL: https://www.google.com/maps?cbll=50,5145821685756,14,1384198131743&cbp=12,90,0,0,5&layer=c
than it becomes URL: https://www.google.com/maps/@0,0,3a,75y,90h,85t/data=!3m3!1e1!3m1!2e0

**Comment by notebooker** [comment]
First it generates this URL:
![image](https://user-images.githubusercontent.com/6602747/32786909-82269334-c955-11e7-91be-093d2b100f42.png)
than it becomes this:
![image](https://user-images.githubusercontent.com/6602747/32786947-9a8a7ecc-c955-11e7-96ac-4cc0d32e8f88.png)

**Comment by green3g** [comment]
So here's an easy workaround, but I'm guessing you don't want to do this since it will make all your decimals be formatted with a " . "

![image](https://user-images.githubusercontent.com/5471079/32789066-78494486-c920-11e7-946b-e83cf81c002c.png)

**Comment by green3g** [comment]
Can you see if this fixes the issue? https://github.com/roemhildtg/arcgis-pro-addins/releases/tag/1.0.1

**Comment by notebooker** [comment]
Wow, this fix work like a charm! You're great!
For future, I suggest that If I had map with different coordinate system than WGS84 or Web Mercator this tool donť use the transformation of coordinates system that I define in map properties. So If I use map with S-JTSK Krovak East North system (WKID 5514) and even the transformation S JTSK To WGS 1984 1, it takes the StreetView to litle bit different location, I think the add-in takes no transformation. But it's not serious problem, just an idea for future development. If I had some time, I will borrow your script and try to make own widget...
Thanks for your great work!

**Comment by green3g** [comment]
Haha, it was a pretty easy fix. Yeah, I'm not sure what would be necessary to do the transformation...haven't really looked into that much. But if you figure it out, I'd definitely take a pull request
